language: ruby
sudo: false
rvm:
  - 2.3.5
  - 2.4.2
gemfile:
  - gemfiles/rails_4x.gemfile
  - gemfiles/rails_5x.gemfile
branches:
  only:
    - master
before_install:
  - gem update --system --no-doc
